<?php

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_5d24ac7455b79',
	'title' => 'Öppettider',
	'fields' => array(
		array(
			'key' => 'field_5d24ac8349e7c',
			'label' => 'Titel',
			'name' => 'box1_title',
			'type' => 'text',
			'instructions' => 'Kort titel, max 24 tecken.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Öppettider',
			'placeholder' => 'Öppettider',
			'prepend' => '',
			'append' => '',
			'maxlength' => 24,
		),
		array(
			'key' => 'field_5d2721e9ece73',
			'label' => 'Bild',
			'name' => 'box1_img',
			'type' => 'image',
			'instructions' => 'Första bilden på startsidan.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_5d24b737bd93f',
			'label' => 'Sektion 1',
			'name' => 'box1_open1',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_5d24b810d1672',
					'label' => 'Underrubrik',
					'name' => 'title',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => 'À la carte',
					'placeholder' => 'À la carte',
					'prepend' => '',
					'append' => '',
					'maxlength' => 32,
				),
				array(
					'key' => 'field_5d24b841d1673',
					'label' => 'Dag(ar) 1',
					'name' => 'days1',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33.333',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'Dag',
					'prepend' => '',
					'append' => '',
					'maxlength' => 12,
				),
				array(
					'key' => 'field_5d24b91c5af78',
					'label' => 'Tid (öppning)',
					'name' => 'days1_open',
					'type' => 'time_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33.333',
						'class' => '',
						'id' => '',
					),
					'display_format' => 'H:i',
					'return_format' => 'H:i',
				),
				array(
					'key' => 'field_5d24b9a65af79',
					'label' => 'Tid (stängning)',
					'name' => 'days1_close',
					'type' => 'time_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33.333',
						'class' => '',
						'id' => '',
					),
					'display_format' => 'H:i',
					'return_format' => 'H:i',
				),
				array(
					'key' => 'field_5d24b88ed1674',
					'label' => 'Dag(ar) 2',
					'name' => 'days2',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5d24b841d1673',
								'operator' => '!=empty',
							),
						),
					),
					'wrapper' => array(
						'width' => '33.333',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'Dag',
					'prepend' => '',
					'append' => '',
					'maxlength' => 12,
				),
				array(
					'key' => 'field_5d24bacf96974',
					'label' => 'Tid (öppning)',
					'name' => 'days2_open',
					'type' => 'time_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5d24b841d1673',
								'operator' => '!=empty',
							),
						),
					),
					'wrapper' => array(
						'width' => '33.333',
						'class' => '',
						'id' => '',
					),
					'display_format' => 'H:i',
					'return_format' => 'H:i',
				),
				array(
					'key' => 'field_5d24baeb96975',
					'label' => 'Tid (stängning)',
					'name' => 'days2_close',
					'type' => 'time_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5d24b841d1673',
								'operator' => '!=empty',
							),
						),
					),
					'wrapper' => array(
						'width' => '33.333',
						'class' => '',
						'id' => '',
					),
					'display_format' => 'H:i',
					'return_format' => 'H:i',
				),
				array(
					'key' => 'field_5d24b8b6d1675',
					'label' => 'Dag(ar) 3',
					'name' => 'days3',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5d24b88ed1674',
								'operator' => '!=empty',
							),
						),
					),
					'wrapper' => array(
						'width' => '33.333',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'Dag',
					'prepend' => '',
					'append' => '',
					'maxlength' => 12,
				),
				array(
					'key' => 'field_5d24bb2096977',
					'label' => 'Tid (öppning)',
					'name' => 'days3_open',
					'type' => 'time_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5d24b88ed1674',
								'operator' => '!=empty',
							),
						),
					),
					'wrapper' => array(
						'width' => '33.333',
						'class' => '',
						'id' => '',
					),
					'display_format' => 'H:i',
					'return_format' => 'H:i',
				),
				array(
					'key' => 'field_5d24bb3296978',
					'label' => 'Tid (stängning)',
					'name' => 'days3_close',
					'type' => 'time_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5d24b88ed1674',
								'operator' => '!=empty',
							),
						),
					),
					'wrapper' => array(
						'width' => '33.333',
						'class' => '',
						'id' => '',
					),
					'display_format' => 'H:i',
					'return_format' => 'H:i',
				),
			),
		),
		array(
			'key' => 'field_5d24bcaef659d',
			'label' => 'Sektion 2',
			'name' => 'box1_open2',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_5d24bcaef659e',
					'label' => 'Underrubrik',
					'name' => 'title',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => 'Lunch',
					'placeholder' => 'Lunch',
					'prepend' => '',
					'append' => '',
					'maxlength' => 32,
				),
				array(
					'key' => 'field_5d24bcaef659f',
					'label' => 'Dag(ar) 1',
					'name' => 'days1',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33.333',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'Dag',
					'prepend' => '',
					'append' => '',
					'maxlength' => 12,
				),
				array(
					'key' => 'field_5d24bcaef65a0',
					'label' => 'Tid (öppning)',
					'name' => 'days1_open',
					'type' => 'time_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33.333',
						'class' => '',
						'id' => '',
					),
					'display_format' => 'H:i',
					'return_format' => 'H:i',
				),
				array(
					'key' => 'field_5d24bcaef65a1',
					'label' => 'Tid (stängning)',
					'name' => 'days1_close',
					'type' => 'time_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33.333',
						'class' => '',
						'id' => '',
					),
					'display_format' => 'H:i',
					'return_format' => 'H:i',
				),
				array(
					'key' => 'field_5d24bcaef65a2',
					'label' => 'Dag(ar) 2',
					'name' => 'days2',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5d24bcaef659f',
								'operator' => '!=empty',
							),
						),
					),
					'wrapper' => array(
						'width' => '33.333',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'Dag',
					'prepend' => '',
					'append' => '',
					'maxlength' => 12,
				),
				array(
					'key' => 'field_5d24bcaef65a3',
					'label' => 'Tid (öppning)',
					'name' => 'days2_open',
					'type' => 'time_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5d24bcaef659f',
								'operator' => '!=empty',
							),
						),
					),
					'wrapper' => array(
						'width' => '33.333',
						'class' => '',
						'id' => '',
					),
					'display_format' => 'H:i',
					'return_format' => 'H:i',
				),
				array(
					'key' => 'field_5d24bcaef65a4',
					'label' => 'Tid (stängning)',
					'name' => 'days2_close',
					'type' => 'time_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5d24bcaef659f',
								'operator' => '!=empty',
							),
						),
					),
					'wrapper' => array(
						'width' => '33.333',
						'class' => '',
						'id' => '',
					),
					'display_format' => 'H:i',
					'return_format' => 'H:i',
				),
				array(
					'key' => 'field_5d24bcaef65a5',
					'label' => 'Dag(ar) 3',
					'name' => 'days3',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5d24bcaef65a2',
								'operator' => '!=empty',
							),
						),
					),
					'wrapper' => array(
						'width' => '33.333',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'Dag',
					'prepend' => '',
					'append' => '',
					'maxlength' => 12,
				),
				array(
					'key' => 'field_5d24bcaef65a6',
					'label' => 'Tid (öppning)',
					'name' => 'days3_open',
					'type' => 'time_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5d24bcaef65a2',
								'operator' => '!=empty',
							),
						),
					),
					'wrapper' => array(
						'width' => '33.333',
						'class' => '',
						'id' => '',
					),
					'display_format' => 'H:i',
					'return_format' => 'H:i',
				),
				array(
					'key' => 'field_5d24bcaef65a7',
					'label' => 'Tid (stängning)',
					'name' => 'days3_close',
					'type' => 'time_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5d24bcaef65a2',
								'operator' => '!=empty',
							),
						),
					),
					'wrapper' => array(
						'width' => '33.333',
						'class' => '',
						'id' => '',
					),
					'display_format' => 'H:i',
					'return_format' => 'H:i',
				),
			),
		),
		array(
			'key' => 'field_5d24bf3671482',
			'label' => 'Sektion 3',
			'name' => 'box1_open3',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_5d24bf3671483',
					'label' => 'Underrubrik',
					'name' => 'title',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => 'Nattklubb',
					'placeholder' => 'Nattklubb',
					'prepend' => '',
					'append' => '',
					'maxlength' => 32,
				),
				array(
					'key' => 'field_5d24bf3671484',
					'label' => 'Dag(ar) 1',
					'name' => 'days1',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33.333',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'Dag',
					'prepend' => '',
					'append' => '',
					'maxlength' => 12,
				),
				array(
					'key' => 'field_5d24bf3671485',
					'label' => 'Tid (öppning)',
					'name' => 'days1_open',
					'type' => 'time_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33.333',
						'class' => '',
						'id' => '',
					),
					'display_format' => 'H:i',
					'return_format' => 'H:i',
				),
				array(
					'key' => 'field_5d24bf3671486',
					'label' => 'Tid (stängning)',
					'name' => 'days1_close',
					'type' => 'time_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33.333',
						'class' => '',
						'id' => '',
					),
					'display_format' => 'H:i',
					'return_format' => 'H:i',
				),
				array(
					'key' => 'field_5d24bf3671487',
					'label' => 'Dag(ar) 2',
					'name' => 'days2',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5d24bf3671484',
								'operator' => '!=empty',
							),
						),
					),
					'wrapper' => array(
						'width' => '33.333',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'Dag',
					'prepend' => '',
					'append' => '',
					'maxlength' => 12,
				),
				array(
					'key' => 'field_5d24bf3671488',
					'label' => 'Tid (öppning)',
					'name' => 'days2_open',
					'type' => 'time_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5d24bf3671484',
								'operator' => '!=empty',
							),
						),
					),
					'wrapper' => array(
						'width' => '33.333',
						'class' => '',
						'id' => '',
					),
					'display_format' => 'H:i',
					'return_format' => 'H:i',
				),
				array(
					'key' => 'field_5d24bf3671489',
					'label' => 'Tid (stängning)',
					'name' => 'days2_close',
					'type' => 'time_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5d24bf3671484',
								'operator' => '!=empty',
							),
						),
					),
					'wrapper' => array(
						'width' => '33.333',
						'class' => '',
						'id' => '',
					),
					'display_format' => 'H:i',
					'return_format' => 'H:i',
				),
				array(
					'key' => 'field_5d24bf367148a',
					'label' => 'Dag(ar) 3',
					'name' => 'days3',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5d24bf3671487',
								'operator' => '!=empty',
							),
						),
					),
					'wrapper' => array(
						'width' => '33.333',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'Dag',
					'prepend' => '',
					'append' => '',
					'maxlength' => 12,
				),
				array(
					'key' => 'field_5d24bf367148b',
					'label' => 'Tid (öppning)',
					'name' => 'days3_open',
					'type' => 'time_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5d24bf3671487',
								'operator' => '!=empty',
							),
						),
					),
					'wrapper' => array(
						'width' => '33.333',
						'class' => '',
						'id' => '',
					),
					'display_format' => 'H:i',
					'return_format' => 'H:i',
				),
				array(
					'key' => 'field_5d24bf367148c',
					'label' => 'Tid (stängning)',
					'name' => 'days3_close',
					'type' => 'time_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5d24bf3671487',
								'operator' => '!=empty',
							),
						),
					),
					'wrapper' => array(
						'width' => '33.333',
						'class' => '',
						'id' => '',
					),
					'display_format' => 'H:i',
					'return_format' => 'H:i',
				),
			),
		),
		array(
			'key' => 'field_5d24c1bbaa5d0',
			'label' => 'Sektion 4',
			'name' => 'box1_open4',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_5d24c1bbaa5d1',
					'label' => 'Underrubrik',
					'name' => 'title',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => 'After work',
					'placeholder' => 'After work',
					'prepend' => '',
					'append' => '',
					'maxlength' => 32,
				),
				array(
					'key' => 'field_5d24c1bbaa5d2',
					'label' => 'Dag(ar) 1',
					'name' => 'days1',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33.333',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'Dag',
					'prepend' => '',
					'append' => '',
					'maxlength' => 12,
				),
				array(
					'key' => 'field_5d24c1bbaa5d3',
					'label' => 'Tid (öppning)',
					'name' => 'days1_open',
					'type' => 'time_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33.333',
						'class' => '',
						'id' => '',
					),
					'display_format' => 'H:i',
					'return_format' => 'H:i',
				),
				array(
					'key' => 'field_5d24c1bbaa5d4',
					'label' => 'Tid (stängning)',
					'name' => 'days1_close',
					'type' => 'time_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33.333',
						'class' => '',
						'id' => '',
					),
					'display_format' => 'H:i',
					'return_format' => 'H:i',
				),
				array(
					'key' => 'field_5d24c1bbaa5d5',
					'label' => 'Dag(ar) 2',
					'name' => 'days2',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5d24c1bbaa5d2',
								'operator' => '!=empty',
							),
						),
					),
					'wrapper' => array(
						'width' => '33.333',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'Dag',
					'prepend' => '',
					'append' => '',
					'maxlength' => 12,
				),
				array(
					'key' => 'field_5d24c1bbaa5d6',
					'label' => 'Tid (öppning)',
					'name' => 'days2_open',
					'type' => 'time_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5d24c1bbaa5d2',
								'operator' => '!=empty',
							),
						),
					),
					'wrapper' => array(
						'width' => '33.333',
						'class' => '',
						'id' => '',
					),
					'display_format' => 'H:i',
					'return_format' => 'H:i',
				),
				array(
					'key' => 'field_5d24c1bbaa5d7',
					'label' => 'Tid (stängning)',
					'name' => 'days2_close',
					'type' => 'time_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5d24c1bbaa5d2',
								'operator' => '!=empty',
							),
						),
					),
					'wrapper' => array(
						'width' => '33.333',
						'class' => '',
						'id' => '',
					),
					'display_format' => 'H:i',
					'return_format' => 'H:i',
				),
				array(
					'key' => 'field_5d24c1bbaa5d8',
					'label' => 'Dag(ar) 3',
					'name' => 'days3',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5d24c1bbaa5d5',
								'operator' => '!=empty',
							),
						),
					),
					'wrapper' => array(
						'width' => '33.333',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'Dag',
					'prepend' => '',
					'append' => '',
					'maxlength' => 12,
				),
				array(
					'key' => 'field_5d24c1bbaa5d9',
					'label' => 'Tid (öppning)',
					'name' => 'days3_open',
					'type' => 'time_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5d24c1bbaa5d5',
								'operator' => '!=empty',
							),
						),
					),
					'wrapper' => array(
						'width' => '33.333',
						'class' => '',
						'id' => '',
					),
					'display_format' => 'H:i',
					'return_format' => 'H:i',
				),
				array(
					'key' => 'field_5d24c1bbaa5da',
					'label' => 'Tid (stängning)',
					'name' => 'days3_close',
					'type' => 'time_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5d24c1bbaa5d5',
								'operator' => '!=empty',
							),
						),
					),
					'wrapper' => array(
						'width' => '33.333',
						'class' => '',
						'id' => '',
					),
					'display_format' => 'H:i',
					'return_format' => 'H:i',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'page_type',
				'operator' => '==',
				'value' => 'front_page',
			),
		),
	),
	'menu_order' => 1,
	'position' => 'acf_after_title',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => 'På startsidan',
));

acf_add_local_field_group(array(
	'key' => 'group_5d24b0179b126',
	'title' => 'Om Glädje',
	'fields' => array(
		array(
			'key' => 'field_5d24b0845fc86',
			'label' => 'Titel',
			'name' => 'box2_title',
			'type' => 'text',
			'instructions' => 'Kort titel, max 24 tecken.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Om Glädje',
			'placeholder' => 'Om Glädje',
			'prepend' => '',
			'append' => '',
			'maxlength' => 24,
		),
		array(
			'key' => 'field_5d2722fa2ee6a',
			'label' => 'Bild',
			'name' => 'box2_img',
			'type' => 'image',
			'instructions' => 'Andra bilden på startsidan.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_5d24b0ae5fc87',
			'label' => 'Text',
			'name' => 'box2_text',
			'type' => 'textarea',
			'instructions' => 'Kort beskrivande text om Glädje.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => 4,
			'new_lines' => 'wpautop',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'page_type',
				'operator' => '==',
				'value' => 'front_page',
			),
		),
	),
	'menu_order' => 2,
	'position' => 'acf_after_title',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => 'På startsidan',
));

acf_add_local_field_group(array(
	'key' => 'group_5d249ed75a961',
	'title' => 'After work',
	'fields' => array(
		array(
			'key' => 'field_5d24ade55470a',
			'label' => 'Titel',
			'name' => 'box3_title',
			'type' => 'text',
			'instructions' => 'Kort titel, max 24 tecken.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'After work',
			'placeholder' => 'After work',
			'prepend' => '',
			'append' => '',
			'maxlength' => 24,
		),
		array(
			'key' => 'field_5d272323d482c',
			'label' => 'Bild',
			'name' => 'box3_img',
			'type' => 'image',
			'instructions' => 'Tredje bilden på startsidan. Endast synlig i datorversionen, ej mobil.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_5d24ae155470b',
			'label' => 'Dag(ar)',
			'name' => 'box3_days',
			'type' => 'text',
			'instructions' => 'Ange dag(ar) för after work.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33.333',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Fredagar',
			'placeholder' => 'Fredagar',
			'prepend' => '',
			'append' => '',
			'maxlength' => 12,
		),
		array(
			'key' => 'field_5d24ae5a5470c',
			'label' => 'Tid (öppning)',
			'name' => 'box3_open',
			'type' => 'time_picker',
			'instructions' => 'Ange tid då after work öppnar.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33.333',
				'class' => '',
				'id' => '',
			),
			'display_format' => 'H:i',
			'return_format' => 'H:i',
		),
		array(
			'key' => 'field_5d24aebd5470d',
			'label' => 'Tid (stängning)',
			'name' => 'box3_close',
			'type' => 'time_picker',
			'instructions' => 'Ange tid då after work stänger.',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5d24ae5a5470c',
						'operator' => '!=empty',
					),
				),
			),
			'wrapper' => array(
				'width' => '33.333',
				'class' => '',
				'id' => '',
			),
			'display_format' => 'H:i',
			'return_format' => 'H:i',
		),
		array(
			'key' => 'field_5d24af7e78edf',
			'label' => 'Text',
			'name' => 'box3_text',
			'type' => 'textarea',
			'instructions' => 'Kort beskrivande text om after worken.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'Välkommen till After Work på Glädje...',
			'maxlength' => '',
			'rows' => 4,
			'new_lines' => 'wpautop',
		),
		array(
			'key' => 'field_5d24b1e216c33',
			'label' => 'Länktext',
			'name' => 'box3_link',
			'type' => 'text',
			'instructions' => 'Text på länken som leder till den angivna url-adressen.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Läs mer & se prislista',
			'placeholder' => 'Läs mer',
			'prepend' => '',
			'append' => '',
			'maxlength' => 32,
		),
		array(
			'key' => 'field_5d2711e1aa37d',
			'label' => 'Länk-url',
			'name' => 'box3_url',
			'type' => 'url',
			'instructions' => 'Url som leder vidare till en annan sida.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '/aw',
			'placeholder' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'page_type',
				'operator' => '==',
				'value' => 'front_page',
			),
		),
	),
	'menu_order' => 3,
	'position' => 'acf_after_title',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => 'På startsidan',
));

endif;

?>